import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BlurredCircle from "@/components/BlurredCircle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Panthera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${inter.className}`}>
        <div className="container mx-auto w-[1400px]">
          <Header />
          <BlurredCircle />
          {children}
        </div>
      </body>
    </html>
  );
}
