import Head from "next/head";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import LayoutBlurredCircle from "@/components/LayoutBlurredCircle";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pantheras",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <LayoutBlurredCircle />
        <div className="overflow-x-hidden container mx-auto 2xl:w-[1400px]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
